### ISSUE TITLE
openshift-sync-plugin - forced proxy envVars in PodTemplates

### ISSUE THREAD

**Issue by bszeti** [openshift/jenkins#1000] opened 2019-12-18 21:37 UTC
A new feature was added to Jenkins _openshift-sync-plugin-1.0.43_ adding http proxy related env variables to all Kubernetes plugin PodTemplate:
- http_proxy
- https_proxy
- no_proxy

If these env vars are not set on Jenkins master, they are added to the Jenkins agent pods with empty string. See commit 
https://github.com/jenkinsci/openshift-sync-plugin/commit/e847b36f14e2fb9174e568ded99b7763c4776e2a

This can break agents that used to work before. Here is the scenario I run into.
The Jenkins agent image has these env vars baked in the image:
- HTTP_PROXY=http://myproxy:9090
- http_proxy=http://myproxy:9090
- HTTPS_PROXY=http://myproxy:9090
- https_proxy=http://myproxy:9090
- NO_PROXY=.mycompany.com
- no_proxy=.mycompany.com

With the extra automatically added "lower case" proxy variables to PodTemplate, these are the env vars we see during using the agent:
- https_proxy=http://myproxy:9090
- NO_PROXY=10.7.185.170,10.7.40.190
The IPs in NO_PROXY are the Jenkins http and jnlp service IPs - instead of the expected "NO_PROXY=10.7.185.170,10.7.40.190,.mycompany.com"

This causes any HTTPS call fail that would fall under the domains in the original $NO_PROXY and should not go through the $https_proxy.

**Why is this happening?**
The extra PodTemplate empty envVars of course overwrite the ones from the image, so what we have in the container is:
- HTTP_PROXY=http://myproxy:9090
- http_proxy=
- HTTPS_PROXY=http://myproxy:9090
- https_proxy=
- NO_PROXY=.mycompany.com
- no_proxy=
Probably some Jenkins script takes tha $no_proxy and appends the jnlp+http IP addresses and overwrites the $NO_PROXY env var. (Also overwrites the $HTTP_PROXY with the value of $http_proxy)

Workaround of course to set the no_proxy, http_proxy, https_proxy env vars in the PodTemplate, but that's extra maintenance and was not needed previously.

**Comment by waveywaves** [comment] 2019-12-20 07:18
@bszeti This has been fixed in the sync plugin and will be fixed in the next release.

**Comment by bszeti** [comment] 2019-12-20 07:20
Great news, thanks. Can you point me to the fix by any chance? Is it in
Jenkins plugin or something in the agent base?

**Comment by bszeti** [comment] 2020-01-02 14:10
I took a look at [PodTemplateUtils.java](https://github.com/jenkinsci/openshift-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/PodTemplateUtils.java) in master, but I don't see any new code change. @waveywaves Can you please explain the fix you mentioned?

**Comment by bszeti** [comment] 2020-01-03 16:27
I've seen a Kubernetes Plugin configuration option under Advanced saying "Transfer proxy related environment variables from master to agent", but disabling it doesn't seem to have an impact. The http proxy parameters are still transferred to the agent's PodTemplate.

**Comment by waveywaves** [comment] 2020-01-13 07:01
@bszeti We are testing the newer fix right now. This was partially being caused by an bug in Jenkins.save() functionality which has been mediated in the latest release of Jenkins. 

We would be updating the sync plugin soon. Will let you know as we are done with it.

**Comment by jbodswor** [comment] 2020-03-11 22:34
Has this been fixed yet?  I am also having this issue.

**Comment by waveywaves** [comment] 2020-03-16 09:58
@jbodswor The issue was fixed in https://github.com/openshift/jenkins-sync-plugin/pull/368 
What version of sync plugin are you on ? Are you facing this issue in 1.0.44 ? 

@bszeti Are you still facing this issue ?

**Comment by jbodswor** [comment] 2020-03-19 05:25
Yes, still having trouble.  Upgraded Jenkins to the following...
---
Container Image: registry.redhat.io/openshift3/jenkins-2-rhel7:v3.11.170-5
Jenkins Version: 2.204.2
Openshift Sync: 1.0.44
---
All kubernetes pod templates have the empty lowercase http_proxy, https_proxy, and no_proxy EnvVars settings added (set to null).  Manually removing them only commits the change to the 2 custom slaves that I have configured.  The maven and nodejs default slave pods definitions will not save the EnvVars removal.  I assume that these values are either being synced elsewhere or inherited.

**Comment by jr00n** [comment] 2020-03-25 06:57
Haveing same problem. 

`2020-03-25 06:42:57.545+0000 [id=96]	INFO	i.f.j.o.PodTemplateUtils#setProxyEnvVar: Adding Proxy EnvVar for Template nodejs10
2020-03-25 06:42:57.546+0000 [id=96]	WARNING	i.f.j.o.ConfigMapWatcher#eventReceived: Caught: java.lang.NullPointerException
java.lang.NullPointerException
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplate.setEnvVars(PodTemplate.java:490)
	at io.fabric8.jenkins.openshiftsync.PodTemplateUtils.setProxyEnvVar(PodTemplateUtils.java:190)`

Not specifying any EnvVars and the Jenkins pod has no NO_PROXY or HTTPS_PROXY env variables

**Closed** 2020-12-03 03:39 UTC
Labels: lifecycle/rotten
