### ISSUE TITLE
jenkins-2-centos7 sync plugin error - No field label conversion function

### ISSUE THREAD

**Issue by eformat** [openshift/jenkins#386] opened 2017-09-25 09:42 UTC
hi, the latest  jenkins-2-centos7 image fails to run properly (it starts OK, but won't start slave images) on vanilla OCP - v3.6.173.0.21. looks like a sync plugin issue ?

error in jenkins pod logs:

Sep 25, 2017 9:39:42 AM io.fabric8.jenkins.openshiftsync.BuildWatcher$1 doRun
--
  | SEVERE: Failed to load initial Builds: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default/apis/build.openshift.io/v1/namespaces/petstore/builds?fieldSelector=status%3DNew. Message: No field label conversion function found for version: build.openshift.io/v1. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=No field label conversion function found for version: build.openshift.io/v1, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default/apis/build.openshift.io/v1/namespaces/petstore/builds?fieldSelector=status%3DNew. Message: No field label conversion function found for version: build.openshift.io/v1. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=No field label conversion function found for version: build.openshift.io/v1, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
  | at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:97)
  | at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
  | at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Sep 25, 2017 9:39:42 AM io.fabric8.jenkins.openshiftsync.ImageStreamWatcher$1 doRun

-- using jenkins image

oc import-image --all --insecure=true --confirm -n openshift docker.io/openshift/jenkins-2-centos7

ose:~$ oc describe is jenkins-2-centos7 -n openshift
Name:			jenkins-2-centos7
Namespace:		openshift
Created:		2 hours ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2017-09-25T07:17:39Z
Docker Pull Spec:	172.30.1.1:5000/openshift/jenkins-2-centos7
Image Lookup:		local=false
Unique Images:		2
Tags:			2

latest
  tagged from docker.io/openshift/jenkins-2-centos7:latest
    will use insecure HTTPS or HTTP connections

  * docker.io/openshift/jenkins-2-centos7@sha256:b8cbb037dc5c1d1f0d47327b7b0f7f4949c7e264402bb8fa7b1bdc8fe71feecc
      2 hours ago

with openshift configured as:

jenkinsPipelineConfig:
  autoProvisionEnabled: true
  parameters:
    JENKINS_IMAGE_STREAM_TAG: jenkins-2-centos7:latest
    ENABLE_OAUTH: "true"
  serviceName: jenkins
  templateName: jenkins-persistent
  templateNamespace: openshift

**Comment by bparees** [comment] 2017-09-25 12:39
dupe of https://github.com/openshift/jenkins-sync-plugin/issues/173

**Closed by bparees** 2017-09-25 12:39 UTC
