### ISSUE TITLE
Use of Kubernetes cluster information env vars for configuring Kubernetes plugin is brittle at handling IP changes

### ISSUE THREAD

**Issue by andyfeller** [openshift/jenkins#858] opened 2019-05-24 11:57 UTC
## Problem

Whenever the Jenkins master is first being configured, the [Kubernetes plugin is autoconfigured](https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L26) based on the [current K8s `Service` IP address representing the Jenkins master](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L16
), however there are scenarios when the `Service` IP address will change out from under the user and thus causing agent builds to break until someone debugs the problem and manually reconfigures the plugin.

IANA K8s expert so I can't really elaborate when `Service`s get re-IP'd.  My only thought on how to solve this is by using the K8s `Service` hostname(s) instead.

Thoughts?

## References

[Source of K8s configuration](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L16)
```
JNLP_SERVICE_NAME=${JNLP_SERVICE_NAME:-JENKINS_JNLP}
JNLP_SERVICE_NAME=`echo ${JNLP_SERVICE_NAME} | tr '[a-z]' '[A-Z]' | tr '-' '_'`
T_HOST=${JNLP_SERVICE_NAME}_SERVICE_HOST
# the '!' handles env variable indirection so we can resolve the nested variable
# see: http://stackoverflow.com/a/14204692
JNLP_HOST=${!T_HOST}
T_PORT=${JNLP_SERVICE_NAME}_SERVICE_PORT
JNLP_PORT=${!T_PORT}

export JNLP_PORT=${JNLP_PORT:-50000}

# pull from 4.0 payload env in image registry; we no longer
# provide a default when running this image outside of openshift;
# other configuration changes (like the SA) were needed as well
# anyway
export NODEJS_SLAVE=${NODEJS_SLAVE_IMAGE:-image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-nodejs:latest}
export MAVEN_SLAVE=${MAVEN_SLAVE_IMAGE:-image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven:latest}

JENKINS_SERVICE_NAME=${JENKINS_SERVICE_NAME:-JENKINS}
JENKINS_SERVICE_NAME=`echo ${JENKINS_SERVICE_NAME} | tr '[a-z]' '[A-Z]' | tr '-' '_'`

J_HOST=${JENKINS_SERVICE_NAME}_SERVICE_HOST
JENKINS_SERVICE_HOST=${!J_HOST}

J_PORT=${JENKINS_SERVICE_NAME}_SERVICE_PORT
JENKINS_SERVICE_PORT=${!J_PORT}
```

[K8s plugin configuration template](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L146)
```
      <serverUrl>https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}</serverUrl>
      <skipTlsVerify>false</skipTlsVerify>
      <addMasterProxyEnvVars>true</addMasterProxyEnvVars>
      <serverCertificate>${crt_contents}</serverCertificate>
      <namespace>${PROJECT_NAME}</namespace>
      <jenkinsUrl>http://${JENKINS_SERVICE_HOST}:${JENKINS_SERVICE_PORT}</jenkinsUrl>
      <jenkinsTunnel>${JNLP_HOST}:${JNLP_PORT}</jenkinsTunnel>
```

## Version information
**affects**: all versions of openshift/jenkins
**openshift/jenkins image**: openshift/jenkins-2-centos7:v3.11
**openshift info**:
```
me@me-mbp ~ $ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server ...
openshift v3.11.43
kubernetes v1.11.0+d4cacc0
```

**Comment by gabemontero** [comment] 2019-05-24 16:39
@bparees do you remember if there were specific reasons that  the service IP was used in the k8s plugin configuration vs. inferring the hostname of 

`<svcname>/<namespace>/.svc:<svc port>`

Certainly using the default values when jenkins is provisioned in the `jenkins` namespace, the host name `jenkins-jnlp.jenkins.svc:50000` was resolvable via `curl`

**Comment by bparees** [comment] 2019-05-24 16:49
is the namespace discoverable within the pod?  at a minimum you may have to explicitly inject it.  and for the k8s service you're kinda on your own(ie at risk of breakage) if you start using an assumed name for the service, instead of the injected service env var.

otherwise no, i don't recall a particular reason.

**Comment by gabemontero** [comment] 2019-05-24 16:53
On Fri, May 24, 2019 at 12:50 PM Ben Parees <notifications@github.com>
wrote:

> is the namespace discoverable within the pod? at a minimum you may have to
> explicitly inject it. and for the k8s service you're kinda on your own(ie
> at risk of breakage) if you start using an assumed name for the service,
> instead of the injected service env var.
>
Sorry, I would use the injected service env var to get the name.  And yes
the namespace is discoverable.  So grab those 2, along with the port, and
build the string around the ".svc" suffix, and use that as the hostname.

**Comment by bparees** [comment] 2019-05-24 16:58
the kubernetes service env var being injected is a special case though.  normally only services in your namespace are injected as env vars into your pod.

so i think there's no guarantee that just because you have an env var named "KUBERNETES_SERVICE_HOST" that there is a service hostname "kubernetes.default.svc"  (it could also move out of the default namespace which would break your logic)

that is for the k8s service of course.  for the jenkins services you have more control and they are not special cases, so building them up could be ok.  That said, i don't think service ips are supposed to change unless you delete/recreate the service...so it's interesting that this is coming up as an issue at all..it might be worth figuring out why it's happening to @andyfeller before we make changes.

**Comment by andyfeller** [comment] 2019-05-25 01:49
@bparees : I honestly have no idea as we're only reapplying a variant of https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-persistent-template.json#L223 where the only thing that is likely to have change is a version label we apply to all resources; for example: `1.7.1`.  This is only the 2nd time we've seen this issue in hundreds over ~2 years, so it is pretty rare and nothing is being deleted.  I assume like y'all that the Service IP should only change if it is deleted and recreated, however IANA Kubernetes networking guru 🤷‍♂

**Comment by gabemontero** [comment] 2019-05-29 14:36
thanks for the info @andyfeller 

taking into account
- we have control over the jenkins service as @bparees noted
- given the rarity of the occurrences as @andyfeller 

we'll put this on the list of to-do's but not at the highest priority ... and it feels like a good educational exercise for the devtools folks coming on if I can't get to it in the short term.

@waveywaves @sthaha  fyi ^^

**Comment by andyfeller** [comment] 2019-05-31 08:06
Definitely understand and think that’s reasonable, thanks Gabe!

I really wish I had more info about what’s going on as I would like to have something definitive.

**Comment by akram** [comment] 2019-06-12 13:13
@andyfeller we weirdly also faced this issue this week with @waveywaves  .
We will be investigating also. Could you please give more information about your k8s plugin version also?
and k8s or openshift version ? if you still have them.

**Comment by andyfeller** [comment] 2019-06-12 21:21
@akram We're using the 1.14.9 version of the Jenkins Kubernetes plugin.  All of the OpenShift information is at the top of the issue.  I believe we saw this as early as 1.14.3 but this isn't an issue with kicking off the Jenkins agent; the Jenkins master `Service` being re-IPed is the problem in question, which is out of bounds of the K8s plugin purview

**Comment by akram** [comment] 2019-06-13 15:58
As you intuited, @andyfeller per design, the k8s `Service` cannot be re-IPed unless the service is deleted and re-created. This is why I was trying to investigate other causes, like the Kubernetes plugin configuration getting overriden from somewhere else.

We saw something similar to what you have seen: for some reason, the JENKINS_URL of our plugin configuration was pointing to http://non_existing_service_ip:8080 .

And we checked the Service creation timestamp, it was several weeks old. So definitely, it was not a re-creation.

Do you have any trace or log of a Service IP change ? or even history of your services / IP / namespaces ?

**Comment by andyfeller** [comment] 2019-06-14 09:08
Thanks Akram for looking into this, btw.

I wish I had some smoking gun to offer but don’t.  I’ll try digging into Elastic Stack to see if there’s anything but what I can tell you is that the template is reapplied to update Jenkins; we never delete the Service.  I’ll keep it in mind as we do Jenkins upgrades to look out for.

**Comment by waveywaves** [comment] 2019-06-24 20:20
@gabemontero @andyfeller  To reproduce the issue where the pods pick up the wrong service name.
1> Create a jenkins-persistent deployment wiht the template.
- New services and config.xml in the pv are created
2> Delete using `oc delete all -l app=jenkins-persistent`
- Services are deleted, pvc stays intact
3> Create a jenkins-persistent deployment again in the same namespace and see that no new jobs are created. 
- New services are created with different clusterIPs, config.xml has the old service IP for jenkins-jnlp service present in the `<jenkinsUrl>` tag. Which would be used by Kubernetes-plugin to create Pod Templates which would try to communicate wiht the `jenkins-jnlp` service.

Should validate the jenkinsUrl in the /var/lib/jenkins/config.xml if the config.xml already exists and override the service. For this we can set an env variable which does the checking. It can be disabled if the users would like to give their own IP for the Jenkins service.

**Comment by andyfeller** [comment] 2019-06-24 20:58
Just to clarify: we don’t delete the Deployment, Sevice, etc in rolling out upgrades, so this isn’t reproducing our use cases.

**Closed** 2020-11-11 08:12 UTC
Labels: kind/feature, lifecycle/rotten
