### ISSUE TITLE
s2i build of jenkins does not know the installed plugins since they are only linked in the run script

### ISSUE THREAD

**Issue by bakito** [openshift/jenkins#451] opened 2017-12-20 12:15 UTC
I'm customizing the openshift jenkins by using the s2i build as described here: https://docs.openshift.com/container-platform/3.6/using_images/other_images/jenkins.html#jenkins-as-s2i-builder 

Since this commit (
https://github.com/openshift/jenkins/commit/f7b3afb30f027d29c6bbf46f56a345e7f87e0a8c#diff-e6dcb991982488881a38bc0d22e481a0 line 208ff) the installation of plugins during s2i build does not work correctly, because at assembly time the pre-installed plugins are not yet visible for the install-plugin.sh script.

Depending on what plugins get installed, some dependent plugins with a much lower version get installed, because the do not exist for the script.

When the container is started, the links from the base installation are created, which leads to an inconsistent and unusable jeknins instance.

To assure the s2i is working correctly, the links should also/already be made from the assembly script.

**Comment by gabemontero** [comment] 2017-12-20 13:08
On Wed, Dec 20, 2017 at 7:15 AM, Marc Brugger <notifications@github.com>
wrote:

> I'm customizing the openshift jenkins by using the s2i build as described
> here: https://docs.openshift.com/container-platform/3.6/using_
> images/other_images/jenkins.html#jenkins-as-s2i-builder
>
> Since this commit (
> f7b3afb#diff-e6dcb991982488881a38bc0d22e481a0
> <https://github.com/openshift/jenkins/commit/f7b3afb30f027d29c6bbf46f56a345e7f87e0a8c#diff-e6dcb991982488881a38bc0d22e481a0>)
> the installation of plugins during s2i build does not work correctly,
> because at assembly time the pre-installed plugins are not yet visible for
> the install-plugin.sh script.
>
> Depending on what plugins get installed, some dependent plugins with a
> much lower version get installed, because the do not exist for the script.
>
> When the container is started, the links from the base installation are
> created, which leads to an inconsistent and unusable jeknins instance.
>
Must be the move of the linking out of the Dockerfile and into the start up
path.  Our s2i testing did not catch the nuance above @bparees.

First blush, refactor the new (re)linking bash logic into a separate .sh
file that we call from the Dockerfile.

**Comment by gabemontero** [comment] 2017-12-20 13:26
Oh, and to be clear, we still leave the processing that does exist in `install_plugins.sh` to still support the upgrade scenarios that were fixed with https://github.com/openshift/jenkins/commit/f7b3afb30f027d29c6bbf46f56a345e7f87e0a8c#diff-e6dcb991982488881a38bc0d22e481a0

we just add the link back into the Dockerfile to facilitate this scenario

**Comment by gabemontero** [comment] 2017-12-20 13:29
@bakito - would you be able to provide a precise `s2i` invocation that we could use as a reproduce / validator?

**Comment by bakito** [comment] 2017-12-20 13:37
[plugins.txt](https://github.com/openshift/jenkins/files/1575655/plugins.txt)

This is the output of a s2i build with the delivered image from redhat, where the base plugins are not linked. The summary in the end lists much less plugins than actualli are installed on the jenkins once it is started. 36 plugins are installed.
[s2i-log-without-base-plugins.log](https://github.com/openshift/jenkins/files/1575649/s2i-log-without-base-plugins.log)

This s2i log is based on an image that has the links to the base plugins done in the Dockerfile. As result, not so many transitive plugin have to be installed (8 plugins installed), since they are already available in a newer version.
[s2i-log-with-links-to-base-plugins.log](https://github.com/openshift/jenkins/files/1575650/s2i-log-with-links-to-base-plugins.log)

**Comment by gabemontero** [comment] 2017-12-20 13:42
thanks @bakito !

and just to be certain there are no disconnects, what is the ID and sha of the base image you used?

**Comment by bakito** [comment] 2017-12-20 13:46
Name: openshift3/jenkins-2-rhel7
Summary: Provides the latest release of Red Hat Enterprise Linux 7 in a fully featured and supported base image.
Description: Jenkins is a continuous integration server
Source URL:  https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/jenkins-2-rhel7/images/v3.7.14-5
Author: Ben Parees <bparees@redhat.com>
Built: 7 days ago
Digest: sha256:39484e2ba9798759c173c9dc1d432b2de7559d0c0697f980d849a29f72707079
Identifier: f4981f86bde13e8065e108d0d1dabc45667b17ac2fb1acf7f261c0a698a34456

**Comment by gabemontero** [comment] 2017-12-20 14:25
plan on having a PR with the links back in the Dockerfile, adjustments to the automated testing to ensure "base" plugins are there, as well as manual testing of the PV upgrade scenario, sometime today

**Comment by gabemontero** [comment] 2017-12-20 15:28
ok, existing jenkins image tests are passing for me locally (both rhel and centos), and I've manually verified @bakito 's scenario with the fix.

automating the verification is a bit trickier since the existing test's starting off s2i image adds the base plugins ... I believe we'll need to add a dummy assemble script that does the base plugin file check, but I don't have that sorted out yet.

Have to run to an appointment but will complete upgrade scenario test when I get back.

Although certainly not ideal, a work around of including the contents of our base-plugins.txt into the plugins.txt consumed by s2i can do the trick.

**Comment by gabemontero** [comment] 2017-12-20 17:54
ok, upgrade scenario with PV's still works with the link re-inserted into the dockerfile, but with the install-plugins.sh logic unchanged

sorting out additions to the tests to catch the issue, and will then craft a PR

**Comment by gabemontero** [comment] 2017-12-20 18:57
duh .. the assemble is in the builder image ... ok, punting on including verification in automated test

**Comment by bparees** [comment] 2017-12-21 00:20
> duh .. the assemble is in the builder image ... ok, punting on including verification in automated test

it is, but you can provide your own assemble script as part of the inputs to the build (by providing one in your repo)
https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#override-builder-image-scripts

**Closed** 2017-12-22 15:39 UTC

**Comment by gabemontero** [comment] 2018-01-04 15:42
Hey @bakito - see https://github.com/openshift/jenkins/pull/455#issuecomment-355314838 regarding when we expect to see the jenkins-2-rhel7 image updated with the fix for this at registry.access.redhat.com
