### ISSUE TITLE
Pass ENV Var to the podTemplate

### ISSUE THREAD

**Issue by cmoulliard** [openshift/jenkins#290] opened 2017-05-08 10:05 UTC
Since OCP 3.6 we can pass [ENV vars](https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#jenkins-pipeline-strategy-environment) to the BuildConfig/Pipeline but I don't see within the Jenkins 2 Docker image that the maven PodTemplate used to configure the pod where the build will take place as described within a groovy pipeline script will be able to reuse such ENV vars.

Is there a trick to pass them or do we have to update this file to [support it](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L154) ?

**Comment by bparees** [comment] 2017-05-08 12:53
The env vars should be available to the pipeline(executing within the slave pod) w/o having to configure the env vars in the pod template explicitly...  I would expect Jenkins to ensure the env vars being provided to the pipeline execution, are provided to it regardless of where the pipeline is executing.

Have you actually seen an issue?  Can you describe in more detail what you are doing (what variable you're setting, how you're using it in your pipeline)?

Adding @gabemontero

**Comment by cmoulliard** [comment] 2017-05-08 13:20
> Can you describe in more detail

Here is the scenario that we are following.

- Every new project created within an openshift namespace will get a Jenkins Server using the jenkins ephemeral or persistent template available in Openshift
- A Buildconfig object containing a JenkinsPipelineStrategy will be created using this [template](https://github.com/cmoulliard/launchpad-missioncontrol/blob/master/services/openshift-service-impl/src/main/resources/pipeline-template.yml#L58) where the git repo corresponds to by example this project [created](https://github.com/cmoulliard/zz1/blob/master/Jenkinsfile)
- When a build is triggered (= pipeline build), jenkins will use this [slave image](https://github.com/openshiftio/launchpad-jenkins-slave-dockerfile/blob/master/Dockerfile) to create the maven jnlp slave pod where the build will take place. This pod is created using the kubernetes jenkins plugin based on the podTemplate defined [here](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L73)

As you can see the PodTemplate defined within the script kube-slave-common.sh contains an <envVars> section that we would like to configure to pass a Build env var or param (e.g. MAVEN_MIRROR_URL)

```
<envVars>
      <org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>
        <key>MAVEN_MIRROR_URL</key>
        <value>${MAVEN_MIRROR_URL}</value>
      </org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>
</envVars>
```

**Comment by cmoulliard** [comment] 2017-05-08 13:56
The only that I have been able to find for the moment to resolve this problem is to : 

1) Change the DeploymentConfig file created from the Jenkins Template to pass the MAVEN_MIRROR_URL env var

```
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: jenkins
  namespace: zz1
  labels:
    template: jenkins-persistent-template
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - jenkins
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'jenkins:latest'
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins
      containers:
        - name: jenkins
          image: 'openshift/jenkins-2-centos7:latest'
          env:
            - name: OPENSHIFT_ENABLE_OAUTH
              value: 'true'
...
            - name: MAVEN_MIRROR_URL
              value: 'http://localhost:8080/nexus'
```
2) Update the PodTemplate `launch-maven` to pass an additional ENV var to be used by Kubernetes Jenkins Plugin when it will create ou pod responsible to do the build

<img width="1515" alt="screenshot 2017-05-08 15 55 19" src="https://cloud.githubusercontent.com/assets/463790/25807355/d7cd5712-3406-11e7-82b4-eeebb23ff529.png">

**Comment by gabemontero** [comment] 2017-05-08 20:50
I've confirmed things are woking as we would hope an appropriate 3.6 version of origin and the latest openshift/jenkins-2-centos7 image (though any openshift jenkins image with v0.1.11 of the sync plugin should suffice) for adding env vars to pipeline build strategy builds, where the env vars will be propagated to any jenkins slaves referenced by the jenkinsfile. 

Here is a simple build config:

```
apiVersion: v1
kind: Template
labels:
  template: application-template-sample-pipeline
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-pipeline-example
parameters:
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: sample-pipeline-withenvs
    name: sample-pipeline-withenvs
  spec:
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: FOO1
            value: BAR1
        jenkinsfile: |-
          node("maven") {
            echo "FOO1 is ${env.FOO1}"
            echo "FOO2 is ${env.FOO2}"
          }
      type: JenkinsPipeline
```

And here is the job output (which is what is expected):

```
In progressConsole Output

OpenShift Build myproject/sample-pipeline-withenvs-1
[Pipeline] node
Still waiting to schedule task
maven-16947a123fe5 is offline
Running on maven-16947a123fe5 in /tmp/workspace/myproject-sample-pipeline-withenvs
[Pipeline] {
[Pipeline] echo
FOO1 is BAR1
[Pipeline] echo
FOO2 is null
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

Now, I am not sure I entirely understand the scenario description @cmoulliard outlined.  In particular,

1) when describing the <envVars> sample that could go in the k8s plugin's PodTemplate, did you mean that would be a *default* setting for `MAVEN_MIRROR_URL`, and that you wished to then override this value via the specific Jenkinsfiles / BuildConfig ?

2) Or were you proposing that as a solution in lieu of using the env vars now available for openshift pipeline strategy builds?

If 2), then hopefully you can just mimic the example I pasted above.

If 1), then I am not sure what would take precedence.  I attempted to try it out, but am currently blocked by https://github.com/openshift/jenkins-sync-plugin/issues/132

**Comment by cmoulliard** [comment] 2017-05-09 14:05
> the pipeline buildconfig env variable

I have been able to setup a project where the ENV var is defined within the Buildconfig object and passed finally to the jenkins slave pod when the Kubernetes Jenkins Plugin will create the maven pod using this template definition generated when the jenkins server is [created](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L78-L108)

Here is the scenario tested successfully using OCP 1.6 on Minishift 1.0.0

```
# Use Minishift 1.0.0.RC

minishift delete
minishift config set memory 4096
minishift config set openshift-version v3.6.0-alpha.1
minishift start

oc login -u developer -p developer

eval $(minishift docker-env)
docker pull openshift/jenkins-2-centos7
docker pull openshiftio/launchpad-jenkins-slave
docker pull sonatype/nexus

echo "Setup Nexus application"
oc new-project infra
oc new-app sonatype/nexus
oc expose svc/nexus
oc volumes dc/nexus --add --name 'nexus-volume-1' --type 'pvc' --mount-path '/sonatype-work/' --claim-name 'nexus-pv' --claim-size '1G' --overwrite

echo "Create demo project containing Jenkins Pipeline & Jenkins Server"
echo "Replace within the following BuildConfig the Github project that you want to use AND http address of your Nexus Server"
oc new-project demo
echo "See jenkins centos docker doc - script kubernetes shell"
#oc policy add-role-to-user edit system:serviceaccount:demo:default
#oc policy add-role-to-user admin system:serviceaccount:demo:jenkins

echo "Create ImageStream"
cat << EOF | oc create -f - 
apiVersion: v1
kind: ImageStream
metadata:
  name: launchpad-maven
  annotations:
    openshift.io/display-name: 'Jenkins 2 CentOS 7'
  labels:
    role: jenkins-slave
spec:
  dockerImageRepository: openshiftio/launchpad-jenkins-slave
  tags:
  - from:
      kind: DockerImage
      name: openshiftio/launchpad-jenkins-slave:latest
    name: latest
    referencePolicy:
      type: Source
EOF

oc new-app --template=jenkins-persistent -n demo

echo "Edit Jenkins Conf System to define for launch-maven kubernetes pod template this ENV var"
Key: MAVEN_MIRROR_URL
Val: ${MAVEN_MIRROR_URL}

https://www.dropbox.com/s/a0nxmew0igo72ee/Screenshot%202017-05-08%2017.48.59.png?dl=0

echo #Trigger a new Jenkins Deployment to reload the modification other jenkins build will hang. To be investigated !!!"
oc rollout latest dc/jenkins

echo "Create Buildconfig"
cat << EOF | oc create -f - 
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind":
      "DeploymentConfig"}]'
  name: demo
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/cmoulliard/zz1.git
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: MAVEN_MIRROR_URL
          value: http://nexus-infra.192.168.64.25.nip.io/nexus/content/groups/public/
  triggers:
  - type: ConfigChange
  - github:
      secret: "1494236915073"
    type: GitHub
EOF
```

**Comment by gabemontero** [comment] 2017-05-09 14:07
OK, if I read @cmoulliard update correctly, I think we are good here.  Closing out.

**Comment by bparees** [comment] 2017-05-09 14:15
hm.  Sounds to me like @cmoulliard still manually set the env key/value on the slave pod template, in addition to setting it on the buildconfig:

```
echo "Edit Jenkins Conf System to define for launch-maven kubernetes pod template this ENV var"
Key: MAVEN_MIRROR_URL
Val: ${MAVEN_MIRROR_URL}
```

That step should not be necessary (and is the pain point that I think @cmoulliard was concerned with in the first place).

@cmoulliard can you confirm whether you actually need to do that?

**Comment by cmoulliard** [comment] 2017-05-09 14:18
> when describing the sample that could go in the k8s plugin's PodTemplate, did you mean that would be a default setting for MAVEN_MIRROR_URL, and that you wished to then override this value via the specific Jenkinsfiles / BuildConfig ?

There is no such default value for the moment define within the docker image but a test checking if there is a MAVEN_MIRROR_URL [var](https://github.com/cmoulliard/jenkins/blob/master/slave-maven/contrib/bin/configure-slave). A default value is not required

```
#!/bin/bash

if [ -n "$MAVEN_MIRROR_URL" ]; then
  xml="    <mirror>\
    <id>mirror.default</id>\
    <url>$MAVEN_MIRROR_URL</url>\
    <mirrorOf>external:*</mirrorOf>\
  </mirror>"
  sed -i "s|<!-- ### configured mirrors ### -->|$xml|" $HOME/.m2/settings.xml
fi
```

**Comment by cmoulliard** [comment] 2017-05-09 14:20
> whether you actually need to do that?

Yes. This manuel step is still required.

**Comment by gabemontero** [comment] 2017-05-09 14:21
@cmoulliard  posted in comment https://github.com/openshift/jenkins/issues/290#issuecomment-300175060this link:  https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L78-L108

where there is not env var set in the pod template.  I was working off that.

**Comment by gabemontero** [comment] 2017-05-09 14:22
And his build config *does* have the env var set.

**Comment by cmoulliard** [comment] 2017-05-09 14:22
> concerned

Ideally, the shell script should be updated to include a test and add <envVars> or <volumes> section 

Here is the example that I'm using in my forked project to use the env var (code to check is not yet there like also for the volumes)

```
# convert_is_to_slave converts the OpenShift imagestream to a Jenkins Kubernetes
# Plugin slave configuration.
function convert_is_to_slave() {
  [ -z "$oc_cmd" ] && return
  local name=$1
  local template_file=$(mktemp)
  local template="
  <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
    <inheritFrom></inheritFrom>
    <name>{{.metadata.name}}</name>
    <instanceCap>5</instanceCap>
    <idleMinutes>0</idleMinutes>
    <label>{{if not .metadata.annotations}}${name}{{else}}{{if index .metadata.annotations \"slave-label\"}}{{index .metadata.annotations \"slave-label\"}}{{else}}${name}{{end}}{{end}}</label>
    <serviceAccount>${oc_serviceaccount_name}</serviceAccount>
    <nodeSelector></nodeSelector>
    <volumes>
      <org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim>
        <mountPath>/home/jenkins/.m2</mountPath>
        <claimName>jenkins-maven</claimName>
        <readOnly>false</readOnly>
      </org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim>
    </volumes>
    <containers>
      <org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
        <name>jnlp</name>
        <image>{{.status.dockerImageRepository}}</image>
        <privileged>false</privileged>
        <alwaysPullImage>false</alwaysPullImage>
        <workingDir>/tmp</workingDir>
        <command></command>
        <args>\${computer.jnlpmac} \${computer.name}</args>
        <ttyEnabled>false</ttyEnabled>
        <resourceRequestCpu></resourceRequestCpu>
        <resourceRequestMemory></resourceRequestMemory>
        <resourceLimitCpu></resourceLimitCpu>
        <resourceLimitMemory></resourceLimitMemory>
        <envVars/>
      </org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
    </containers>
    <envVars>
      <org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>
        <key>MAVEN_MIRROR_URL</key>
        <value>${MAVEN_MIRROR_URL}</value>
      </org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>
    </envVars>
    <annotations/>
    <imagePullSecrets/>
    <nodeProperties/>
  </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
  "
  echo "${template}" > ${template_file}
  $oc_cmd get -n "${PROJECT_NAME}" is/${name} -o templatefile --template ${template_file}
  rm -f ${template_file} &>/dev/null
}
```

**Comment by gabemontero** [comment] 2017-05-09 14:29
OK, I am going to circle back to my request for clarification in https://github.com/openshift/jenkins/issues/290#issuecomment-299986922

And try to restate the first part of the question more directly:

@cmoulliard - are you setting the `MAVEN_MIRROR_URL` env var in *BOTH* the PodTemplate env var section and the BuildConfig env var section, and then executing a job with both in place?

I've seen you paste both a BuildConfig and PodTemplate with env vars defined.

**Comment by cmoulliard** [comment] 2017-05-09 14:33
> a job with both in place?

Yes. This is required as the env var defined within the buildconfig will be passed to the jenkins pod created and subsequently used by the shell script - kube-slave-common.sh

**Comment by gabemontero** [comment] 2017-05-09 14:40
OK, once I am unblocked by https://github.com/openshift/jenkins-sync-plugin/issues/132, I will construct such a flow and report back.

**Comment by cmoulliard** [comment] 2017-05-09 16:48
Hmm. The problem is more complex as we we can imagine as the shell script will use the content of the var "template" to fill the variables from the ImageStream discovered within the namespace.

```
$oc_cmd get -n "${PROJECT_NAME}" is/${name} -o templatefile --template ${template_file}
```

So, if the imagestream doesn't contain the vars that we want to change, I don't see how the template processed by go will be able to check if an env var exist to mount a volume, set the MAVEN_MIRROR_URL ... and how we could do something like this 

```
if [ -z "${MAVEN_MIRROR_URL}" ]; then
      <envVars>
        <org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>
          <key>MAVEN_MIRROR_URL</key>
          <value>${MAVEN_MIRROR_URL}</value>
       </org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>
      </envVars>
      fi
```

An alternative could be to process the content of the PodTemplate in 2 steps; 1) bash shell & 2) go template replacement

**Comment by bparees** [comment] 2017-05-09 17:44
> Yes. This is required as the env var defined within the buildconfig will be passed to the jenkins pod created and subsequently used by the shell script -> kube-slave-common.sh. The podTemplate which is used by kubernetes jenkins plugin will then use the env var defined within the section 

that's not how that works, unless your scenario is much more complicated than i'm envisioning.

Your goal, as i understand it, is to make the MAVEN_MIRROR_URL value available to your pipeline logic when it is executing.  As it happens, you're executing that logic on a slave pod (vs on the jenkins master).

here's a test i just ran using a pipeline buildconfig that uses a maven slave pod and echoes the $FOO variable that's defined in the buildconfig.  The slave pod template is the default from the image:

```
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    pipeline.alpha.openshift.io/uses: '[{"name": "nodejs-mongodb-example", "namespace":
      "", "kind": "DeploymentConfig"}]'
  creationTimestamp: 2017-05-09T17:39:12Z
  labels:
    app: jenkins-pipeline-example
    name: sample-pipeline
    template: application-template-sample-pipeline
  name: sample-pipeline
  namespace: c1
  resourceVersion: "1198"
  selfLink: /oapi/v1/namespaces/c1/buildconfigs/sample-pipeline
  uid: 6a4ce074-34de-11e7-8438-507b9d27b5d9
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: FOO
        value: BAR
      jenkinsfile: |-
        node('nodejs') {
          stage('build') {
            sh 'echo $FOO'
          }
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
```

and here's the output from the job:

```
OpenShift Build c1/sample-pipeline-1
[Pipeline] node

Running on nodejs-293cfc1ebf92 in /tmp/workspace/c1-sample-pipeline
[Pipeline] {
[Pipeline] stage
[Pipeline] { (build)

[Pipeline] sh

[c1-sample-pipeline] Running shell script
+ echo BAR
BAR
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

So as you can see, the FOO variable value(BAR), as defined in the buildconfig, was available to the pipeline logic running on the maven slave pod.

**Comment by bparees** [comment] 2017-05-09 17:45
(sorry, I see I used the nodejs slave pod, not the maven one, but that is immaterial as far as the question at hand goes).

**Comment by gabemontero** [comment] 2017-05-09 17:54
On Tue, May 9, 2017 at 1:45 PM Ben Parees <notifications@github.com> wrote:

> (sorry, I see I used the nodejs slave pod, not the maven one, but that is
> immaterial as far as the question at hand goes).
>
@bparees what you did was exactly like my origina attempt, but I did use a
maven slave

My only concern in all this is what happens when env vars are defined in
both the bc and pod template

**Comment by gabemontero** [comment] 2017-05-09 17:55
On Tue, May 9, 2017 at 1:53 PM Gabe Montero <gmontero@redhat.com> wrote:

> On Tue, May 9, 2017 at 1:45 PM Ben Parees <notifications@github.com>
> wrote:
>
>> (sorry, I see I used the nodejs slave pod, not the maven one, but that is
>> immaterial as far as the question at hand goes).
>>
> @bparees what you did was exactly like my origina attempt, but I did use a
> maven slave
>
> My only concern in all this is what happens when env vars are defined in
> both the bc and pod template
>
where my current testing is blocked by the new NPE i found

**Comment by bparees** [comment] 2017-05-09 18:30
> My only concern in all this is what happens when env vars are defined in both the bc and pod template

which is a fair question and we should learn the answer, but i think for @cmoulliard it should not matter (he should not need to be defining the variable in the pod template).

**Comment by cmoulliard** [comment] 2017-05-09 18:48
> i'm envisioning.

The scenario is more complex. 

- MAVEN_MIRROR_URL
The ENV var "MAVEN_MIRROR_URL" passed through the BuildConfig Object is not used within the pipeline but instead used by this [script](https://github.com/openshift/jenkins/blob/master/slave-maven/contrib/bin/configure-slave), part of the Docker jenkins image to configure the settings.xml file (`<mirror>` xml tag) before it is copied within the /home/.m2 directory of the slave pod container created 

- Volume
2 env var keys (= MountPath & VolumeClaim) passed by the BuildConfig object, will be used by the kubernetes slave common script to create the slave pod (according to the node selected which is for us launchpad-maven) & mount the volume that we [need](https://github.com/openshift/jenkins/blob/master/2/contrib/jenkins/kube-slave-common.sh#L86).
The script should be adapted to add a volume base on the env vars passed
  ```
  export MOUNTPATH=${MOUNTPATH}
  export VOLUMECLAIM=${VOLUMECLAIM}

  if [[ -n "$MOUNTPATH" && -n "$VOLUMECLAIM]]; then
    xml="    <org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim>\
        <mountPath>${MOUNTPATH}</mountPath>\
        <claimName>${VOLUMECLAIM}</claimName>\
        <readOnly>false</readOnly>\
      </org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim>
    sed "s|<!-- ### configured volume  ### -->|$xml|" template
  fi
  ```
  The script kube-slave-common.sh is called when the S2I run script is [called](https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L97-L103)

**Comment by bparees** [comment] 2017-05-09 18:59
> 2 env var keys (= MountPath & VolumeClaim) passed by the BuildConfig object, will be used by the kubernetes slave common script to create the slave pod (according to the node selected which is for us launchpad-maven) & mount the volume that we need.

so you want to actually dynamically define the parameters of a slave pod for a given buildconfig.

i think the net is that the "use configmaps to define slave pods" feature we're working on will address this for you, though you'll need to define the configmap along with the buildconfig.  As long as you aren't anticipating changing the env variables each time you trigger a new build for your buildconfig, it should be sufficient.

**Comment by cmoulliard** [comment] 2017-05-10 05:20
As this function "$(generate_kubernetes_config" is [called](https://github.com/cmoulliard/jenkins/blob/master/2/contrib/s2i/run#L98) when the pod/container is created for the jenkins server and not at all when a jenkins slave pod is created, we can't pass such parameters using the BuildConfig object. That makes no sense. 

This is why I'm thinking now that we should define them using (as you propose) a config map where the ConfigMap Name is the name of the imagestream containing the role label "jenkins-slave"

If we use a ConfigMap using as keyword the name of the imagestream which corresponds also to the name of the node() declare within the groovy script, we could change easily the kube-slave-common.sh script (function convert_is_to_slave() {) as such

```
E.g

oc get cm/launchpad-maven -o yaml
apiVersion: v1
data:
  MAVEN_MIRROR_URL: http://localhost:8080/nexus
  MOUNT_PATH: /home/jenkins/.m2
  VOLUME_CLAIM: jenkins-maven
kind: ConfigMap

AND

export MAVEN_MIRROR_URL=$($oc_cmd get  get cm/${name} -o "jsonpath={.data['MAVEN_MIRROR_URL']}")

if [ -n "$MAVEN_MIRROR_URL" ]; then
  xml="    <org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>\
    <key>MAVEN_MIRROR_URL</key>\
    <value>${MAVEN_MIRROR_URL}</value>\
  </org.csanchez.jenkins.plugins.kubernetes.PodEnvVar>"
  sed "s|<!-- ### configured env var ### -->|$xml|" templateFile
fi
```

**Comment by gabemontero** [comment] 2017-05-10 14:10
ok then, closing this out in lieu of the config map feature work ... per the discussion progression in this issue and a sidebar between @bparees and I, I'll track down the orthogonal issue of order of precedence between env vars in the build config vs. pod template

**Comment by bparees** [comment] 2017-05-10 14:11
> As this function "$(generate_kubernetes_config" is called when the pod/container is created for the jenkins server and not at all when a jenkins slave pod is created, we can't pass such parameters using the BuildConfig object. That makes no sense.

The architecture was not intended to support dynamic configuration of jenkins, the idea was that you configure jenkins initially (either by providing your own config, or by letting the system generate the config from its template configuration), and after that you manage the jenkins configuration via standard jenkins mechanisms.  That is why all the jenkins configuration logic only runs once (the first time jenkins starts).

Furthermore, having buildconfigs dynamically define their own slave pods definitely wasn't intended to be a supported use, though I can see the argument for it.  The assumption was that you define your slave pods (via one of the mechanisms we've discussed, including the new one we're working on) and you define your buildconfig/pipeline(jenkinsfile) to reference the appropriate slave pod(jenkins node label).

> If we use a ConfigMap using as keyword the name of the imagestream which corresponds also to the name of the node() declare within the groovy script, we could change easily the kube-slave-common.sh script (function convert_is_to_slave() {) as such

the configmap plan is that you will define the configmap and a plugin running in openshift will watch for new configmaps and define the new slave automatically and reload the jenkins configuration, so the changes would not go into the jenkins startup script.  You can follow that work here: https://trello.com/c/hS9lzo1v

**Closed by gabemontero** 2017-05-10 14:10 UTC
Labels: P2

**Comment by cmoulliard** [comment] 2017-05-10 14:52
> the configmap plan is that you will define the configmap

I like the approach proposed here. Subscribed to the trello card and voted +1 @bparees
