### ISSUE TITLE
JVM 32bit missing

### ISSUE THREAD

**Issue by bszeti** [openshift/jenkins#713] opened 2018-10-04 21:46 UTC
The registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7 image doesn't seem to have 32bit java, but the starter script tries to use that if memory limit <2048m.

'ls -las /usr/lib/jvm' shows only java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64

**Comment by gabemontero** [comment] 2018-10-05 01:58
Just pulled it

`registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7   latest              8bec9699b95e        7 days ago          1.19GB`

Notice it was updated just 7 days ago.

And believe I see the same thing:

```
bash-4.2$ rpm -qa | grep java-1.8.0
rpm -qa | grep java-1.8.0
java-1.8.0-openjdk-headless-1.8.0.181-3.b13.el7_5.x86_64
java-1.8.0-openjdk-javadoc-1.8.0.181-3.b13.el7_5.noarch
java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64
java-1.8.0-openjdk-devel-1.8.0.181-3.b13.el7_5.x86_64
```

I wonder if this is related to https://bugzilla.redhat.com/show_bug.cgi?id=1630265

That found the main jenkins image missing 32bit in the brew-pulp registry.

And sure enough, I see the same thing in the main jenkins 3.10 image that was also pushed 7 days ago:

`registry.access.redhat.com/openshift3/jenkins-2-rhel7                v3.10               86253d8d3c1b        7 days ago          1.18GB`

```
bash-4.2$ rpm -qa | grep java-1.8.0
rpm -qa | grep java-1.8.0
java-1.8.0-openjdk-headless-1.8.0.181-3.b13.el7_5.x86_64
java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64
bash-4.2$ 
```

@adammhaile fyi ... looks like we either need to get some images pulled out of registry.access.redhat.com or get a new image pushed

**Comment by adammhaile** [comment] 2018-10-05 11:35
@gabemontero What version? Just 3.10 or 3.11?
We just did a new 3.11 build which pushed new images. Check those.
Either way, new images will be pushed next time we build for whatever version(s) is broken. I just need to know what version(s) that is.

**Comment by gabemontero** [comment] 2018-10-05 11:45
On Fri, Oct 5, 2018 at 7:35 AM Adam Haile <notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero> What version? Just 3.10 or
> 3.11?
> We just did a new 3.11 build which pushed new images. Check those.
> Either way, new images will be pushed next time we build for whatever
> version(s) is broken. I just need to know what version(s) that is.
>
3.10 for jenkins-2-rhel was broken as was the latetst tag for
jenkins-agent-maven-8 @adamhaile so if we could start a new builds for
those that would be great

I'll do a more thorough examination when I get into the office

**Comment by adammhaile** [comment] 2018-10-05 11:50
We are already in the middle of a 4.0 build. So I'll wait until you've examined it more before queuing up anything else. I would like some certainty that a rebuild is all that's needed.
Also... by latest do you mean 3.11 or 4.0? At least what are you expecting that to be?

**Comment by gabemontero** [comment] 2018-10-05 13:35
@adammhaile with neither 3.11 nor 4.0 GA'ing yet, we would not expect those tags present for the images at registry.access.redhat.com, and I've confirmed that is the case.

Also, there is an oddity we have to maintain for the images, because of a prior problem, where the latest tag == v3.6

In the middle of pulling the images now, should have a comprehensive analysis shortly.

**Comment by gabemontero** [comment] 2018-10-05 13:36
Also, the last time the jenkins images got corrupted, we had to go through the process of removing them from the registry (though that might have been because of the time needed to refresh new ones).

We should sync up with @brenton once we have a precise lay of the land.

**Comment by adammhaile** [comment] 2018-10-05 13:50
@smunilla I feel like this was something you dealt with before ^

**Comment by gabemontero** [comment] 2018-10-05 13:50
OK here are the complete set of images:

```
REPOSITORY                                                           TAG                 IMAGE ID            CREATED             SIZE
registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7   latest              8bec9699b95e        7 days ago          1.19GB
registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7   v3.10               8bec9699b95e        7 days ago          1.19GB
registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7   latest              5eadb373bbf1        7 days ago          1.11GB
registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7   v3.10               5eadb373bbf1        7 days ago          1.11GB
registry.access.redhat.com/openshift3/jenkins-2-rhel7                v3.10               86253d8d3c1b        7 days ago          1.18GB
registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7      latest              5ce887d9bf31        2 weeks ago         1.02GB
registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7      v3.6                5ce887d9bf31        2 weeks ago         1.02GB
registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7     latest              a32c719893f2        2 weeks ago         971MB
registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7     v3.6                a32c719893f2        2 weeks ago         971MB
registry.access.redhat.com/openshift3/jenkins-2-rhel7                latest              d910aff6f4ca        2 weeks ago         1.13GB
registry.access.redhat.com/openshift3/jenkins-2-rhel7                v3.6                d910aff6f4ca        2 weeks ago         1.13GB
registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7     v3.7                16926e48d04f        3 weeks ago         1.51GB
registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7      v3.7                d9f53d59b463        3 weeks ago         1.6GB
registry.access.redhat.com/openshift3/jenkins-2-rhel7                v3.7                59a56eb6b0ba        3 weeks ago         1.65GB
registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7      v3.10               de6e5fba941c        3 weeks ago         1.34GB
registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7     v3.10               0e5fea0a8bf8        3 weeks ago         1.25GB
registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7      v3.9                cf5c0727dfcf        3 weeks ago         1.77GB
registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7     v3.9                4c531cb0416a        3 weeks ago         1.67GB
registry.access.redhat.com/openshift3/jenkins-2-rhel7                v3.9                938fe1a04585        3 weeks ago         1.84GB
```

The ones that are 7 days old are the ones that are missing 32 bit java.

Those "jenkins-agent-*" images where first introduced in release v3.10, so aside from not seeing the earlier versions, their latest tag == v3.10, unlike our older images, where we have to keep latest == v3.6 for migration purposes.

**Comment by gabemontero** [comment] 2018-10-05 13:51
More precisely, here are those 7 day old images listed on by themselves:

registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7   latest              8bec9699b95e        7 days ago          1.19GB
registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7   v3.10               8bec9699b95e        7 days ago          1.19GB
registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7   latest              5eadb373bbf1        7 days ago          1.11GB
registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7   v3.10               5eadb373bbf1        7 days ago          1.11GB
registry.access.redhat.com/openshift3/jenkins-2-rhel7                v3.10               86253d8d3c1b        7 days ago          1.18GB

**Comment by adammhaile** [comment] 2018-10-05 13:53
What about the images on reg-aws? Anything on registry.access is are
released images. I'm curious if the unreleased ones are fine.

**Comment by gabemontero** [comment] 2018-10-05 14:17
Looking at brew-pulp, the 3.10 jenkins image, which is also 7 days old, is missing 32 bit java.

The other releases are fine (where they are either older or younger than the 3.10 image):

The complete inventory for jenkins-2-rhel on brew-pulp:

brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/jenkins-2-rhel7   latest              554009966569        11 hours ago        1.39GB
brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/jenkins-2-rhel7   v3.11               554009966569        11 hours ago        1.39GB
brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/jenkins-2-rhel7   v3.7                c6cbaf883531        42 hours ago        1.68GB
brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/jenkins-2-rhel7   v3.10               86253d8d3c1b        7 days ago          1.18GB
brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/jenkins-2-rhel7   v3.9                772389a2aa4e        2 weeks ago         1.84GB
brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/jenkins-2-rhel7   v3.6                d910aff6f4ca        2 weeks ago         1.13GB

**Comment by gabemontero** [comment] 2018-10-05 14:20
Same with the v3.10 for jenkins-agent-maven-35-rhel7 and jenkins-agent-nodejs-8-rhel7 on brew-pulp ... 7 days old, missing 32 bit java

**Comment by gabemontero** [comment] 2018-10-08 14:22
OK the v3.10 tag for the jenkins-agent-maven-35-rhel7 image have been reverted to the prior version which contains the 32 bit JVM

The image is now:

`registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7                            v3.10               06afbf69c3f1        3 weeks ago         1.38GB
`

My examination of it:

```
gmontero ~ $ docker run -it 06afbf69c3f1 /bin/bash
OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='8796093022207', using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java
OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='8796093022207', using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/bin/javac
bash-4.2$ rpm -qa | grep java-1.8
rpm -qa | grep java-1.8
java-1.8.0-openjdk-headless-1.8.0.181-3.b13.el7_5.x86_64
java-1.8.0-openjdk-javadoc-1.8.0.181-3.b13.el7_5.noarch
java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.i686
java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64
java-1.8.0-openjdk-devel-1.8.0.181-3.b13.el7_5.i686
java-1.8.0-openjdk-headless-1.8.0.181-3.b13.el7_5.i686
java-1.8.0-openjdk-devel-1.8.0.181-3.b13.el7_5.x86_64
bash-4.2$ 
```

Note, the v3.10 tags for the jenkins-2-rhel7 and jenkins-agent-nodejs-8-rhel7 images are still missing 32 bit.  We are working with the RCM team to complete that.

**Comment by gabemontero** [comment] 2018-10-12 18:44
all the relevant v3.10 tags on registry.access.redhat.com have been reverted and have both 32 and 64 bit java

closing this out

**Closed by gabemontero** 2018-10-12 18:44 UTC
